export enum ActionTypes {
  ADD_CART_PRODUCT = 'ADD_CART_PRODUCT',
  REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT',
  COUNT_CART_PRODUCTS_PRICE = 'COUNT_CART_PRODUCTS_PRICE',
  COUNT_CART_PRODUCTS = 'COUNT_CART_PRODUCTS',
  SELECT_CURRENCY = "SELECT_CURRENCY"
  // PRODUCTS_AMOUNT = 'PRODUCTS_AMOUNT'
}
